export const billList = [
    {
        id: 1, 
        name: 'Agyemang Florence',
        task: 'Joshua Tech',
        hours: 7,
        amount: 64,
        status: 'Pending',
    },
    {
        id: 2, 
        name: 'Agyemang Florence',
        task: 'Joshua Tech',
        hours: 7,
        amount: 64,
        status: 'Pending',
    },
    {
        id: 3, 
        name: 'Agyemang Florence',
        task: 'Joshua Tech',
        hours: 7,
        amount: 64,
        status: 'Pending',
    },
    {
        id: 4, 
        name: 'Agyemang Florence',
        task: 'Joshua Tech',
        hours: 7,
        amount: 64,
        status: 'Pending',
    },
    {
        id: 5, 
        name: 'Agyemang Florence',
        task: 'Joshua Tech',
        hours: 7,
        amount: 64,
        status: 'Pending',
    },
    {
        id: 6, 
        name: 'Agyemang Florence',
        task: 'Joshua Tech',
        hours: 7,
        amount: 64,
        status: 'Pending',
    },
]